-- Edit this list to change unlock order. First entry unlocks after 3 total
-- victories (player1 + player2), then every 3 more for the next. Starters
-- (charmander, squirtle, bulbasaur) are always playable and are not listed.
return {
  "bellossom",
  "gastly",
  "wartortle",
  "charmeleon",
  "pichu",
  "froakie",
  "jigglypuff",
  "glastrier",
  "reshiram",
  "zekrom",
  "zapdos",
  "aerodactyl",
  "torchic",
  "articuno",
  "necrozma",
  "volcanion",
  "jolteon",
  "piplup",
  "thundurus",
  "spectrier",
  "steelix",
  "totodile",
  "chikorita",
  "salamence",
  "vulpix",
  "slugma",
  "elekid",
  "blastoise",
  "charizard",
  "rayquaza",
  "blitzle",
  "flareon",
  "rapidash",
  "wigglytuff",
  "bellsprout",
  "venusaur",
  "ivysaur",
  "gengar",
  "dragapult",
  "cofagrigus",
  "haunter",
}
